// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgtladketupwjfanuazb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndGxhZGtldHVwd2pmYW51YXpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MzQwMDAsImV4cCI6MjA3MjMxMDAwMH0.t7Aoj2xFPUzUyYSnuLeRSFQqzD5VISs8HuAqMK9x5bg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});